# Allow the specific GitHub repository (and only that repository) to obtain
# short-lived tokens for this service account via WIF.
resource "google_service_account_iam_binding" "wif" {
  service_account_id = google_service_account.sa.name
  role               = "roles/iam.workloadIdentityUser"

  members = [
    "principalSet://iam.googleapis.com/${var.wif_pool_name}/attribute.repository/${var.repo}",
  ]
}

# Per-repo custom role containing exactly the permissions needed to
# plan/apply this module's examples — nothing more.
resource "google_project_iam_custom_role" "ci_permissions" {
  count = length(var.permissions) > 0 ? 1 : 0

  project     = var.project
  role_id     = local.role_id
  title       = local.repo_name
  description = "Least-privilege role for GitHub Actions CI — ${var.repo}. Generated by pike."
  permissions = var.permissions
}

# Bind the SA to its custom role.
resource "google_project_iam_member" "custom_role" {
  count = length(var.permissions) > 0 ? 1 : 0

  project = var.project
  role    = google_project_iam_custom_role.ci_permissions[0].id
  member  = "serviceAccount:${google_service_account.sa.email}"
}
