locals {
  repo_name  = split("/", var.repo)[1]
  sa_id_raw  = lower(replace(local.repo_name, "_", "-"))
  sa_id      = substr(local.sa_id_raw, 0, 30)
  sa_display = var.description != "" ? var.description : "GitHub Actions — ${var.repo}"

  # Custom role ID: derived from repo name, valid chars only, max 64 chars.
  role_id = substr(replace(replace(local.repo_name, "-", "_"), ".", "_"), 0, 64)
}

resource "google_service_account" "sa" {
  project      = var.project
  account_id   = local.sa_id
  display_name = local.sa_display
}

# Allow the specific GitHub repository (and only that repository) to obtain
# short-lived tokens for this service account via WIF.
resource "google_service_account_iam_binding" "wif" {
  service_account_id = google_service_account.sa.name
  role               = "roles/iam.workloadIdentityUser"

  members = [
    "principalSet://iam.googleapis.com/${var.wif_pool_name}/attribute.repository/${var.repo}",
  ]
}

# Per-repo custom role containing exactly the permissions needed to
# plan/apply this module's examples — nothing more.
resource "google_project_iam_custom_role" "role" {
  count = length(var.permissions) > 0 ? 1 : 0

  project     = var.project
  role_id     = local.role_id
  title       = local.repo_name
  description = "Least-privilege role for GitHub Actions CI — ${var.repo}. Generated by pike."
  permissions = var.permissions
}

# Bind the SA to its custom role.
resource "google_project_iam_member" "custom_role" {
  count = length(var.permissions) > 0 ? 1 : 0

  project = var.project
  role    = google_project_iam_custom_role.role[0].id
  member  = "serviceAccount:${google_service_account.sa.email}"
}
